<!-- breadcrumbs -->
<div class="breadcrumbs">
    <ul>
        <li class="home"><a href="/admin/">Admin</a></li>
        <li><a href="/admin/paginas/index/">Usu&aacute;rio</a></li>
        <li>Atualizar</li>
    </ul>
</div>
<!-- /breadcrumbs -->


<?php
#print_r($_POST['pagina']);
$dadosPage = $_POST['pagina'];
?>



<div class="box-cols">
    <div class="box box-col">
        <div class="headlines">
            <h2><span>Atualizar Dados da P&aacute;gina</span></h2>
        </div>
        <div class="box-content">
            <form class="formBox" method="post" action="/admin/paginas/atualizar/<?php echo $dadosPage['id']; ?>">
                <input type="hidden" value="<?php echo $dadosPage['id']; ?>" name="id" id="id" />

                <fieldset>
                    <div class="clearfix">
                        <div class="lab"><label for="nome-col">Titulo</label></div>
                        <div class="con"><input type="text" class="input" value="<?php echo $dadosPage['titulo']; ?>" name="titulo" id="titulo" /></div>
                    </div>
                    <div class="clearfix">
                        <div class="lab"><label for=email-col">Slug</label></div>
                        <div class="con"><input type="text" class="input" value="<?php echo $dadosPage['slug']; ?>" name="slug" id="slug" /></div>
                    </div>
                    <div class="clearfix">
                        <div class="lab"><label for="nome-col">Texto</label></div>
                        <div class="con"><textarea cols="" rows="" class="textarea wysiwyg" name="texto" id="texto"><?php echo $dadosPage['texto']; ?></textarea></div>
                    </div>

                    <div class="btn-submit"><!-- Submit form -->
                        <input type="submit" value="Atualizar" class="button" />
                        ou <a href="/admin/paginas/index/" class="cancel">Cancelar</a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>