<!-- breadcrumbs -->
<div class="breadcrumbs">
    <ul>
        <li class="home"><a href="/admin/">Admin</a></li>
        <li><a href="/admin/paginas/index/">P&aacute;gina</a></li>
        <li>Cadastrar</li>
    </ul>
</div>
<!-- /breadcrumbs -->



<div class="box-cols">
    <div class="box box-col">
        <div class="headlines">
            <h2><span>Cadastrar P&aacute;gina</span></h2>
        </div>
        <div class="box-content">
            <form class="formBox" method="post" action="/admin/paginas/cadastrar">
                <fieldset>
                    <div class="clearfix">
                        <div class="lab"><label for="nome-col">Titulo</label></div>
                        <div class="con"><input type="text" class="input" value="" name="titulo" id="titulo" /></div>
                    </div>
                    <div class="clearfix">
                        <div class="lab"><label for=email-col">Slug</label></div>
                        <div class="con"><input type="text" class="input" value="" name="slug" id="slug" /></div>
                    </div>
                    <div class="clearfix">
                        <div class="lab"><label for="nome-col">Texto</label></div>
                        <div class="con"><textarea cols="" rows="" class="textarea wysiwyg" name="texto" id="texto"></textarea></div>
                    </div>

                    <div class="btn-submit"><!-- Submit form -->
                        <input type="submit" value="Salvar" class="button" />
                        ou <a href="/admin/paginas/index/" class="cancel">Cancelar</a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>