    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name='robots' content='all, follow' />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <title>Agiltecti Plataform</title>
        <link href="/app/admin/assets/css/default.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/app/admin/assets/css/blue.css" rel="stylesheet" type="text/css" media="screen" /> <!-- color skin: blue / red / green / dark -->
        <link href="/app/admin/assets/css/datePicker.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/app/admin/assets/css/wysiwyg.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/app/admin/assets/css/fancybox-1.3.1.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/app/admin/assets/css/visualize.css" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <body>
    <div id="main">
        <?php $user = isset($_SESSION['id']) ? $_SESSION['id'] : 0; ?>

        <?php if($user >0){ ?>
            <div id="header">
                <div id="logo">
                    <a href="/admin/" title="Go to Homepage"><span>Agiltecti</span></a>
                </div>

                <div id="user">
                    <h2>Administrador <span>(<?php echo $_SESSION['nome']; ?>)</span></h2>
                    <a href="/">meu site</a> | <a href="/admin/usuarios/atualizar/<?php echo $_SESSION['id']; ?>">atualizar</a> | <a href="/admin/login/logout">logout</a>
                </div>
            </div>

        <?php } else { ?>

            <div id="header">
                <div id="logo">
                    <a href="/admin/" title="Go to Homepage"><span>Agiltecti</span></a>
                </div>
            </div>
        <?php } ?>




        <div id="content">

            <?php ContentPlaceHolder(); ?>

        </div>





        <div id="sidebar">
            <!-- mainmenu -->
            <?php if($user >0){ ?>
                <ul id="floatMenu" class="mainmenu">
                    <li class="first"><a href="/admin/">Dashboard</a></li>
                    <li><a href="javascript:;">P&aacute;ginas</a>
                        <ul class="submenu">
                            <li><a href="/admin/paginas/cadastrar/">Nova P&aacute;gina</a></li>
                            <li><a href="/admin/paginas/">Listar Todas</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Usu&aacute;rios</a>
                        <ul class="submenu">
                            <li><a href="/admin/usuarios/cadastrar/">Novo Usu&aacute;rio</a></li>
                            <li><a href="/admin/usuarios/">Listar Todos</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } ?>
            <!-- /.mainmenu -->
        </div>




        <div id="footer">
            <div style="height: 100px;"></div><div class="box"></div>
            <p>&copy; 2016 Agiltecti Plataform | <a href="#main">Jadir Bento</a></p>
        </div>

    </div>
    <!-- /#main -->



    <script type="text/javascript" src="/app/admin/assets/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="/app/admin/assets/js/jquery.dimensions.min.js"></script>

    <!-- // Tabs // -->
    <script type="text/javascript" src="/app/admin/assets/js/ui.core.js"></script>
    <script type="text/javascript" src="/app/admin/assets/js/jquery.ui.tabs.min.js"></script>

    <!-- // Table drag and drop rows // -->
    <script type="text/javascript" src="/app/admin/assets/js/tablednd.js"></script>

    <!-- // Date Picker // -->
    <script type="text/javascript" src="/app/admin/assets/js/date.js"></script>
    <!--[if IE]><script type="text/javascript" src="/app/admin/assets/js/jquery.bgiframe.js"></script><![endif]-->
    <script type="text/javascript" src="/app/admin/assets/js/jquery.datePicker.js"></script>

    <!-- // Wysiwyg // -->
    <script type="text/javascript" src="/app/admin/assets/js/jquery.wysiwyg.js"></script>

    <!-- // Graphs // -->
    <script type="text/javascript" src="/app/admin/assets/js/excanvas.js"></script>
    <script type="text/javascript" src="/app/admin/assets/js/jquery.visualize.js"></script>

    <!-- // Fancybox // -->
    <script type="text/javascript" src="/app/admin/assets/js/jquery.fancybox-1.3.1.js"></script>

    <!-- // File upload // -->
    <script type="text/javascript" src="/app/admin/assets/js/jquery.filestyle.js"></script>

    <script type="text/javascript" src="/app/admin/assets/js/init.js"></script>
</body>
</html>